const PRODUCTCOMPARE = [
  {
    id: 1,
    playername: '쌉쌉',
    playerid: 2,
    price: '100,000,000',
    productleft: 1,
    lowpricecurrent: true,
  },
  {
    id: 2,
    playername: '쌉쌉',
    playerid: 2,
    price: '100,000,000',
    productleft: 1,
    lowpricecurrent: false,
  },
  {
    id: 3,
    playername: '쌉쌉',
    playerid: 2,
    price: '100,000,000',
    productleft: 1,
    lowpricecurrent: false,
  },
  {
    id: 4,
    playername: '쌉쌉',
    playerid: 2,
    price: '100,000,000',
    productleft: 1,
    lowpricecurrent: false,
  },
  {
    id: 5,
    playername: '쌉쌉',
    playerid: 2,
    price: '100,000,000',
    productleft: 1,
    lowpricecurrent: false,
  },
  {
    id: 6,
    playername: '쌉쌉',
    playerid: 2,
    price: '100,000,000',
    productleft: 1,
    lowpricecurrent: false,
  },
  {
    id: 7,
    playername: '쌉쌉',
    playerid: 2,
    price: '100,000,000',
    productleft: 1,
    lowpricecurrent: false,
  },
  {
    id: 8,
    playername: '쌉쌉',
    playerid: 2,
    price: '100,000,000',
    productleft: 1,
    lowpricecurrent: false,
  },
  {
    id: 9,
    playername: '쌉쌉',
    playerid: 2,
    price: '100,000,000',
    productleft: 1,
    lowpricecurrent: false,
  },
  {
    id: 10,
    playername: '쌉쌉',
    playerid: 2,
    price: '100,000,000',
    productleft: 1,
    lowpricecurrent: false,
  },
  {
    id: 11,
    playername: '쌉쌉',
    playerid: 2,
    price: '100,000,000',
    productleft: 1,
    lowpricecurrent: false,
  },
  {
    id: 12,
    playername: '쌉쌉',
    playerid: 2,
    price: '100,000,000',
    productleft: 1,
    lowpricecurrent: false,
  }
]